### ISSUE TITLE
Sporadic NPE during xprism startup

### ISSUE THREAD

**Issue by kleinj** [prismmodelchecker/prism#111]
Sometimes, during xprism startup, there is a NullPointerException recorded in the log output. It doesn't seem to affect the functionality in any way, PRISM continues to start normally.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at userinterface.GUIPrism.processGUIEvent(GUIPrism.java:560)
	at userinterface.util.GUIEventHandler.notifyListeners(GUIEventHandler.java:60)
	at userinterface.GUIPrism.notifyEventListeners(GUIPrism.java:550)
	at userinterface.GUIPlugin.notifyEventListeners(GUIPlugin.java:440)
	at userinterface.model.computation.ParseModelThread$1.run(ParseModelThread.java:72)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

 Might be a race condition where the ParseModelThread is already running, but the rest of the infrastructure is not yet setup correctly.

This NPE is hard to trigger. We had sporadic sightings (without the concrete stack trace). I was able to capture the trace starting xprism via an `ssh -X` remote session, but subsequent runs did not lead to the exception again.

**Comment by kleinj** [comment]
This is related to the WaitParseThread, which reparses the PRISM model in the editor after changes and a timeout taken from the settings. When I lower the timeout to e.g. 10ms (default = 1000ms), more NPEs in other parts are reliably triggered during startup.

I guess the simplest fix would be to postpone the initial start of the WaitParseThread til after the full startup has finished.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at userinterface.simulator.GUISimulator.doEnables(GUISimulator.java:1027)
	at userinterface.simulator.GUISimulator.setComputing(GUISimulator.java:1964)
	at userinterface.simulator.GUISimulator.processGUIEvent(GUISimulator.java:1002)
	at userinterface.util.GUIEventHandler.notifyListeners(GUIEventHandler.java:56)
	at userinterface.GUIPrism.notifyEventListeners(GUIPrism.java:550)
	at userinterface.GUIPlugin.notifyEventListeners(GUIPlugin.java:440)
	at userinterface.model.computation.ParseModelThread$1.run(ParseModelThread.java:72)
	...
```
