### ISSUE TITLE
Explicit Java-generated model import causing unexpected behavior

### ISSUE THREAD

**Issue by landonjefftaylor** [prismmodelchecker/prism#195]
After generating explicit state (.sta) and transition (.tra) files in a Java program, I get unexpected results. It appears PRISM is only producing a single state after processing the input files. Steps to reproduce are as follows:

The following files are generated in a [Java program](https://github.com/formal-verification-research/cex_permute/blob/buildModel/src/SimulateModel.java) which uses the PRISM API to simulate a path and use results from the simulation to construct a model.

- State file: https://github.com/formal-verification-research/cex_permute/blob/buildModel/model.sta
- Transition file: https://github.com/formal-verification-research/cex_permute/blob/buildModel/model.tra
- CSL property file: https://github.com/formal-verification-research/cex_permute/blob/buildModel/pro.csl 
which reads `P=? [ true U[0,100] s5=40 ]`

When I run the following command: 
`prism -importmodel model.tra,sta -exportmodel out.tra,sta,lab -ctmc pro.csl`

It gives the following output on the command line:
```
Version: 4.6
Date: Tue May 24 10:25:41 MDT 2022
Hostname: horace
Memory limits: cudd=1g, java(heap)=1g
Command line: prism -importmodel 'model.tra,sta' -exportmodel 'out.tra,sta,lab' -ctmc pro.csl

Importing model from "model.tra", "model.sta"...
Using specified model type: CTMC

Parsing properties file "pro.csl"...

1 property:
(1) P=? [ true U[0,100] s5=40 ]

Building model...

Computing reachable states...

Reachability (BFS): 1 iterations in 0.00 seconds (average 0.002000, setup 0.00)

Time for model construction: 0.089 seconds.

Warning: Deadlocks detected and fixed in 1 states

Type:        CTMC
States:      1 (1 initial)
Transitions: 1

Rate matrix: 42 nodes (2 terminal), 1 minterms, vars: 20r/20c

Exporting transition matrix in plain text format to file "out.tra"...

Exporting list of reachable states in plain text format to file "out.sta"...

Exporting labels and satisfying states in plain text format to file "out.lab"...

---------------------------------------------------------------------

Model checking: P=? [ true U[0,100] s5=40 ]

Computing probabilities...
Engine: Hybrid

Number of non-absorbing states: 1 of 1 (100.0%)

Building hybrid MTBDD matrix... [levels=20, nodes=42] [2.0 KB]
Adding explicit sparse matrices... [levels=20, num=1, compact] [0.0 KB]
Creating vector for diagonals... [dist=1, compact] [0.0 KB]
Allocating iteration vectors... [3 x 0.0 KB]
TOTAL: [2.0 KB]

Uniformisation: q.t = 1.020000 x 100.000000 = 102.000000
Fox-Glynn: left = 0, right = 160

Starting iterations...

Steady state detected at iteration 1

Iterative method: 1 iterations in 0.00 seconds (average 0.000000, setup 0.00)

Value in the initial state: 0.0

Time for model checking: 0.01 seconds.

Result: 0.0 (value in the initial state)

---------------------------------------------------------------------

Note: There was 1 warning during computation.

```

It appears there is only 1 state and 1 transition generated. The output files reflect that:

out.sta reads as follows:
```
(s1,s2,s3,s4,s5,s6)
0:(-1,-1,-1,-1,-1,-1)
```

out.tra reads as follows:
```
1 1
0 0 1
```

out.lab reads as follows:
```
0="init" 1="deadlock"
0: 0 1
```

I initially suspected the transitions assigned rates of 0.0 were causing the problem, but after manually adjusting them to have different rates, the issue persists. The state with all variables assigned `-1` is an absorbing state, so a transition is constructed from every state into it.

When I update the model.sta file such that the absorbing state has the values `(60,60,60,60,60,60)` rather than all `-1`, the only state which is produced is `(0,49,0,0,40,0)`, a state which does not exist in the model.sta file.

I am able to manually construct toy state and transition files (with small numbers of states and transitions) which appear to work correctly. A test of the explicit model file for [poll2.sm](http://www.prismmodelchecker.org/manual/Appendices/ExplicitModelFiles) also appears to yield correct results.

Is there a reason PRISM may be producing only one state?

**Comment by landonjefftaylor** [comment]
I have attempted to create and import a label file, with the following contents:
```
0="init" 1="deadlock"
0: 0 
40: 1
```

When I call `prism -importmodel model.sta,tra,lab pro.csl`, the following is the command-line output. It appears it has trouble reading a .lab file due to an undefined method.

```
Importing model from "dummy.tra", "dummy.sta", "dummy.lab"...
Using specified model type: CTMC

Parsing properties file "dummy.csl"...

1 property:
(1) P=? [ true U[0,100] s5=40 ]

Building model...
Exception in thread "main" java.lang.NoSuchMethodError: 'common.iterable.FunctionalPrimitiveIterator$OfInt common.IterableStateSet.iterator()'
	at prism.ExplicitFiles2MTBDD.loadLabels(ExplicitFiles2MTBDD.java:699)
	at prism.ExplicitFiles2MTBDD.buildModel(ExplicitFiles2MTBDD.java:242)
	at prism.ExplicitFiles2MTBDD.build(ExplicitFiles2MTBDD.java:140)
	at prism.Prism.doBuildModel(Prism.java:2126)
	at prism.Prism.buildModelIfRequired(Prism.java:2063)
	at prism.Prism.exportTransToFile(Prism.java:2415)
	at prism.PrismCL.doExports(PrismCL.java:731)
	at prism.PrismCL.run(PrismCL.java:347)
	at prism.PrismCL.go(PrismCL.java:215)
	at prism.PrismCL.main(PrismCL.java:2625)
```

**Comment by landonjefftaylor** [comment]
PRISM compiled with no errors when I followed the installation instructions at https://github.com/prismmodelchecker/prism-api

Here's the sequence I followed to install prism:
```
git clone https://github.com/prismmodelchecker/prism prism
cd prism/prism
make
```

I then added the prism/prism folder (/usr/local/prism-src/prism/prism) to my path.

**Comment by merkste** [comment]
Did you install a copy of prism alongside the api package as required?
Does the import not work for this standalone PRISM, too?

For me, the following commandline worked flawlessly:
```
prism -importmodel bug-195/dummy.sta,tra,lab bug-195/pro.csl
```
